### ISSUE TITLE
An nissue on running

### ISSUE THREAD

**Issue by cod3r0k** [Bai-YT/AdaptiveSmoothing#5]
I have an issue with running...

```

  File "/home/xx/AdaptiveSmoothing/comp_autoattack/checks.py", line 4, in <module>
    from autoattack.other_utils import L2_norm
ImportError: cannot import name 'L2_norm' from 'autoattack.other_utils' (/home/xx//anaconda3/lib/python3.11/site-packages/autoattack/other_utils.py)
```

**Comment by Bai-YT** [comment]
Sorry for the delay. Perhaps updating AutoAttack will help? The latest version has this function (see https://github.com/fra31/auto-attack/blob/a39220048b3c9f2cca9a4d3a54604793c68eca7e/autoattack/other_utils.py#L38).
